services:
    slskd:
        image: slskd/slskd
        container_name: slskd
        ports:
          - "5030:5030"
          - "5031:5031"
          - "50300:50300"
        environment:
          - SLSKD_REMOTE_CONFIGURATION=true
          - SLSKD_SLSK_USERNAME=xdlna
          - SLSKD_SLSK_PASSWORD=${SLSK_PASSWORD}
        volumes:
          - ./data/slskd/:/app:Z
          - "/mnt/mediastorage/plex/data/media/music:/music:Z"
        restart: always
    navidrome:
      image: deluan/navidrome:latest
      user: 1000:1000 # should be owner of volumes
      ports:
        - "4533:4533"
      restart: unless-stopped
#      environment:
        # Optional: put your config options customization here. Examples:
        # ND_LOGLEVEL: debug
      volumes:
        - "./data/navidrome:/data:Z"
        - "/mnt/mediastorage/plex/data/media/music:/music:ro"
